apiVersion: v1
kind: Namespace
metadata:
  name: mc-bedrock-server
  labels:
    app: mc-bedrock-server
    
---

apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-server-udp
  labels:
    app: mc-bedrock-server
  namespace: mc-bedrock-server
spec:
  ports:
    - name: mcsb-udp
      port: 19132
      targetPort: 19132
      protocol: UDP
  selector:
    app: mc-bedrock-server
  type: LoadBalancer
  loadBalancerIP: 192.168.1.27

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-bedrock-server
  labels:
    app: mc-bedrock-server
  namespace: mc-bedrock-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mc-bedrock-server
  template:
    metadata:
      labels:
        app: mc-bedrock-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: mc-bedrock-server
          image: itzg/minecraft-bedrock-server:latest
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: EULA
              value: "TRUE"
            - name: SERVER_NAME
              value: "The Bedrock and Roll"
            - name: GAMEMODE
              value: "creative"
            - name: DIFFICULTY
              value: "normal"
            - name: ALLOW_CHEATS
              value: "true"
            - name: MAX_PLAYERS
              value: "15"
            - name: ONLINE_MODE
              value: "true"
            - name: PVP
              value: "false"
            - name: PLAYER_IDLE_TIMEOUT
              value: "0"
            - name: VERSION
              value: "1.18"
            - name: MAX_THREADS
              value: "12"
            - name: VIEW_DISTANCE
              value: "24"
          ports:
            - containerPort: 19132
              name: mcsb-udp
              
      volumes:
        - name: data
          nfs:
            server: 192.168.1.2
            path: /volume50/mcsb
